### ISSUE TITLE
LOOK SICK, but crashes...

### ISSUE THREAD

**Issue by Kolhax** [WieszakWare/InstaGen#5]
It crash at the moment it ask for the email code:
![image](https://user-images.githubusercontent.com/92904192/191168998-3cb42f84-4501-4b10-8b86-c7a5057a9b51.png)

PS: not to hard, but you should make an auto email scrap and verificator, if u want: https://github.com/MainSilent/MailTm
pretty good for the job

**Comment by WieszakWare** [comment]
I will fix it. Maybe today.

**Comment by WieszakWare** [comment]
https://github.com/WieszakWare/InstaGen/releases/tag/1.0.6.6 Fixed Version 1.0.6.6 here

**Comment by Kolhax** [comment]
btw I'll fork their repo, to add an auto mail shit with mailtm

**Comment by WieszakWare** [comment]
I wonder if instagram will not block the account that was created using mailtm. If I check and instagram does not block my account, I will add options to instagen. Otherwise, I will reject the idea
